name: search_screen
description: "A new Flutter project."
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  dynamic_grid_view: ^0.0.1

  # Add other dependencies here if needed
  # Example:
  # provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/